### ISSUE TITLE
Contao 4.6 service

### ISSUE THREAD

**Issue by kehr-solutions** [heimrichhannot/contao-multi-column-editor-bundle#2]
Damit bei Contao 4.6 das Bundle funktioniert, sollte in der Datei

> src/Resources/config/listener.yml

folgende Änderung durchgeführt werden.

alt:
```
services:
    huh.multicolumneditor.listener.hooks:
        class: HeimrichHannot\MultiColumnEditorBundle\EventListener\HookListener
        arguments:
            - "@contao.framework"
```

neu:
```
services:
    huh.multicolumneditor.listener.hooks:
        class: HeimrichHannot\MultiColumnEditorBundle\EventListener\HookListener
        public: true
        arguments:
            - "@contao.framework"
```
